;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-

;; DO NOT EDIT THIS FILE DIRECTLY
;; This is a file generated from a literate programming source file located at
;; https://gitlab.com/zzamboni/dot-doom/-/blob/master/doom.org
;; You should make any changes there and regenerate it from Emacs org-mode
;; using org-babel-tangle (C-c C-v t)

(setq user-full-name "Marty Buchaus"
      user-mail-address "marty@dabuke.com")

(setq-default delete-by-moving-to-trash t)         ; Move to Trash
(setq-default create-lockfiles nil)                ; NO Lockfiles
(setq-default tab-width 4)                         ; Set width for tabs
(setq-default uniquify-buffer-name-style 'forward) ; Uniquify buffer names
(setq-default window-combination-resize t)         ; take new window space from all other windows (not just current)
(setq-default x-stretch-cursor t)                  ; Stretch cursor to the glyph width

(setq undo-limit 80000000)                ; Raise undo-limit to 80Mb
(setq evil-want-fine-undo t)              ; By default while in insert all changes are one big blob. Be more granular
(setq auto-save-default t)                ; Nobody likes to loose work, I certainly don't
(setq inhibit-compacting-font-caches t)   ; When there are lots of glyphs, keep them in memory
(setq truncate-string-ellipsis "…")       ; Unicode ellipsis are nicer than "...", and also save /precious/ space

(delete-selection-mode 1)                 ; Replace selection when inserting text
(display-time-mode 1)                     ; Enable time in the mode-line
(global-subword-mode 1)                   ; Iterate through CamelCase words

(add-hook 'doom-init-ui-hook #'spacemacs/home)
(remove-hook 'org-load-hook #'+org-init-keybinds-h)

(setq ispell-dictionary "en_US")
(setq ispell-personal-dictionary (expand-file-name ".ispell_personal" doom-private-dir))

(setq flycheck-global-modes '(not org-mode))
(add-hook 'doom-init-ui-hook #'spacemacs/home)
(remove-hook 'org-load-hook #'+org-init-keybinds-h)
