; -*- no-byte-compile: t; -*-
;;; $DOOMDIR/packages.el

(package! evil-snipe :disable t)
(package! solaire-mode :disable t)

(package! aggressive-indent)
(package! all-the-icons-dired)
(package! all-the-icons-dired)
(package! company-nginx)
(package! counsel-tramp)
(package! dashboard)
(package! doct)
(package! ebuku)
(package! elfeed-protocol)
(package! jenkinsfile-mode)
(package! khalel)
(package! khardel)
(package! mu4e-column-faces)
(package! mu4e-marker-icons)
(package! mutt-mode)
(package! nginx-mode)
(package! org-edna)
(package! org-noter)
(package! org-noter-pdftools)
(package! org-notifications)
(package! org-pdftools)
(package! org-projectile)
(package! org-ref)
(package! org-roam-bibtex)
(package! org-super-agenda)
(package! org-wild-notifier)
(package! ox-gfm)
(package! paperless)
(package! salt-mode)
(package! systemd)
(package! wakatime-mode)


(package! activity-watch-mode      :recipe (:host github :repo "pauldub/activity-watch-mode"))
(package! i3wm-config-mode         :recipe (:host github :repo "Alexander-Miller/i3wm-Config-Mode"))
(package! org-appear               :recipe (:host github :repo "awth13/org-appear"))
(package! org-ol-tree              :recipe (:host github :repo "Townk/org-ol-tree"))
(package! org-pandoc-import        :recipe (:host github :repo "tecosaur/org-pandoc-import" :files ("*.el" "filters" "preprocessors")))
(package! org-pretty-table         :recipe (:host github :repo "Fuco1/org-pretty-table"))
(package! org-roam-timestamps      :recipe (:host github :repo "ThomasFKJorna/org-roam-timestamps"))
(package! org-roam-ui              :recipe (:host github :repo "org-roam/org-roam-ui" :files ("*.el" "out")))
(package! org-transclusion         :recipe (:host github :repo "nobiot/org-transclusion" :branch "main" :files ("*.el")))
(package! outshine                 :recipe (:host github :repo "alphapapa/outshine"))
(package! vlf                      :recipe (:host github :repo "m00natic/vlfi" :files ("*.el")))
